name: flutter_google_calendar_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  pigeon: ^25.3.2
  permission_handler: ^12.0.0+1
  intl: ^0.20.2

  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.8

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

dependency_overrides:
  analyzer_plugin: ^0.13.1

flutter:

  uses-material-design: true
